### ISSUE TITLE
Adicionar informações

### ISSUE THREAD

**Issue by joffilyfe** [jtav58/lattes-xml-parser#1]
# Documentação

Notei que o projeto não possui nenhuma informação de como utilizar e também sobre o seu propósito. Seria interessante adicionar essas informações ao readme ou a wiki.

Também notei que não há o arquivo de dependências. Se o projeto crescer vai ficar complicado para instalarmos as dependências necessárias.

# Testes

Não há testes no projeto, seria interessante algum tipo de bateria de testes para que você possa garantir o seu funcionamento.

# Help

Com as devidas informações eu poderia ajudar e contribuir com esse projeto, @jtav58 o que você acha?

**Comment by jtav58** [comment]
Realmente, pensei em colocar as instruções de como utilizar o projeto mais pra frente, quando ele estivesse mais estável.

Sobre o propósito, surgiu da necessidade de manipular as informações do CV lattes de uma maneira mais simples (:heart: dicionários), como não encontrei um módulo pensei: "por que não criar um?"

@joffilyfe, toda ajuda é bem vinda! :)

**Comment by joffilyfe** [comment]
@jtav58 Adiciona um requirements.txt ai eu vou poder testar aqui também 👍

**Comment by jtav58** [comment]
@joffilyfe, por enquanto as libs são só da stdlib, acredito que o Python >= 2.7 seja suficiente para testar
